
###
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "correo": "ricardo.munoz@ciberpol.com",
    "clave": "12345"
}

###
GET http://localhost:3000/auth/login HTTP/1.1